

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/SharedComponets/Navbar";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" bg-teal-400 p-2 ">
          <Navbar></Navbar>

        </nav>
        {children}

      </body>
    </html>
  );
}
