

import { Inter ,Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/SharedComponets/Navbar";




const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({weight:['400','700','900'], subsets: ["latin"] });

export const metadata = {
  title:{
    default:'First Next JS',
    template:'%s | First Next JS'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body className={roboto.className}>
        <nav className=" bg-teal-400 p-2 ">
          <Navbar></Navbar>

        </nav>
        {children}

      </body>
    </html>
  );
}
